export const FETCH_STUDENT_RECORD = 'FETCH_STUDENT_RECORDS';
export const REGISTER_STUDENT = 'REGISTER_STUDENT';
export const SET_STUDENT_RECORDS = 'SET_STUDENT_RECORDS'
export const UPDATE_STUDENT_RECORDS = 'UPDATE_STUDENT_RECORDS'